/**
 * setup_finyear.js - configure the Financial Year on GL101000 (Master Financial
 * Calendar setup). The contract REST API CANNOT do this: a PUT to the FinancialYear
 * entity always fails with "FinPeriods: Please configure all the Financial Periods
 * for the Year" because the period grid is generated by UI field-update events that
 * the contract import processor never fires. So we drive the screen.
 *
 *   $env:GRP_BASE/USER/PASS ; $env:NODE_PATH=(npm root -g)
 *   node setup_finyear.js --year 2026 --periods 12 --start 01/01/2026 [--type Month] [--adj] [--dry]
 *
 * View/field ids (from inspect_screen_fields.js --screen GL101000):
 *   edFiscalYearSetup-FirstFinYear | -FinPeriods | -PeriodsStartDate | -PeriodType | -HasAdjustmentPeriod
 */
const { chromium } = require('playwright');
function arg(n,d){ const i=process.argv.indexOf('--'+n); if(i===-1) return d; const v=process.argv[i+1]; return (!v||v.startsWith('--'))?true:v; }
const BASE=(process.env.GRP_BASE||'').replace(/\/+$/,'')+'/', USER=process.env.GRP_USER, PASS=process.env.GRP_PASS;
const SCREEN='GL101000', VIEW='FiscalYearSetup';
const YEAR=arg('year','2026'), PERIODS=arg('periods','12'), START=arg('start','01/01/'+YEAR), PTYPE=arg('type','Month');
const ADJ=arg('adj',false)!==false, DRY=arg('dry',false)!==false, RESET=arg('reset',false)!==false;
const sleep=(pg,ms)=>pg.waitForTimeout(ms);
const cmd=(frame,c)=>frame.evaluate(c=>{const x=document.querySelector(`[data-cmd="${c}"]`); if(x){['mousedown','mouseup','click'].forEach(e=>x.dispatchEvent(new MouseEvent(e,{bubbles:true})));return true;} return false;},c);
// click a short button/label by text (for confirm modals)
const clickText=(frame,re)=>frame.evaluate(rs=>{const r=new RegExp(rs,'i');const el=[...document.querySelectorAll('button,div,span,a')].find(e=>e.children.length===0&&e.getBoundingClientRect().width>0&&r.test((e.textContent||'').trim())&&(e.textContent||'').trim().length<16);if(el){['mousedown','mouseup','click'].forEach(e=>el.dispatchEvent(new MouseEvent(e,{bubbles:true})));return (el.textContent||'').trim();}return null;},re.source);

// resolve the real <input> for a field: some editors ARE the input (edV-F),
// others wrap it in a _text child (date/combo/checkbox). Return a usable id.
async function inputSel(frame,field){
  return frame.evaluate(base=>{
    const cands=[base+'_text', base];
    for(const id of cands){ const e=document.getElementById(id); if(e && e.tagName==='INPUT') return '#'+CSS.escape(id); }
    const wrap=document.getElementById(base); if(wrap){ const inp=wrap.querySelector('input'); if(inp&&inp.id) return '#'+CSS.escape(inp.id); }
    return null;
  }, `ed${VIEW}-${field}`);
}
// commit a text/date/combo editor: fill then Tab to fire the field-updated event.
// returns the committed value, or '(readonly)' / '(no input)' when not editable.
async function setText(pg,frame,field,val){
  const sel=await inputSel(frame,field);
  if(!sel) return '(no input)';
  const ro=await frame.evaluate(s=>{const e=document.querySelector(s);return !e||e.hasAttribute('readonly')||e.getAttribute('enabled')==='false';},sel);
  if(ro) return '(readonly) '+(await frame.evaluate(s=>document.querySelector(s).value,sel));
  const loc=frame.locator(sel).first();
  await loc.click({timeout:8000}).catch(()=>{});
  await loc.fill(''); await loc.fill(String(val));
  await loc.press('Tab');
  await sleep(pg,2000);
  return frame.evaluate(s=>{const e=document.querySelector(s);return e?e.value:null;},sel);
}
const setCombo=setText;
// count generated period rows: data rows inside the periods grid (skip header)
const gridRows=(frame)=>frame.evaluate(()=>{
  const grids=[...document.querySelectorAll('.grid, [class*="grid"]')];
  let max=0;
  for(const g of grids){ const rs=g.querySelectorAll('div[role="row"], tr'); if(rs.length>max) max=rs.length; }
  // also count rows that actually carry a Period Nbr cell value
  const cells=[...document.querySelectorAll('[id*="PeriodNbr"], [class*="period"]')].length;
  return {gridRowEls:max, periodCells:cells};
});

(async()=>{
  if(!BASE||!USER||!PASS){ console.error('ERR: set GRP_BASE/USER/PASS'); process.exit(1); }
  const b=await chromium.launch({headless:true});
  const pg=await (await b.newContext({viewport:{width:1600,height:900}})).newPage();
  pg.on('dialog',d=>{ d.accept().catch(()=>{}); });
  await pg.goto(BASE,{waitUntil:'domcontentloaded',timeout:60000});
  await pg.locator("input[type='text']:visible, input:not([type]):visible").first().fill(USER);
  await pg.locator("input[type='password']:visible").first().fill(PASS);
  await pg.keyboard.press('Enter'); await sleep(pg,6000);
  await pg.goto(`${BASE}Main?ScreenId=${SCREEN}`,{waitUntil:'domcontentloaded',timeout:60000});
  await sleep(pg,11000);
  const findFrame=()=>pg.frames().find(f=>new RegExp(SCREEN+'\\.html').test(f.url()));
  let frame=findFrame(); if(!frame) throw new Error(SCREEN+'.html frame not found');

  // robust confirm: match a clickable whose normalized text == 'Confirm' (button has child whitespace nodes)
  const clickConfirm=(fr)=>fr.evaluate(()=>{
    const els=[...document.querySelectorAll('button,a,div,span,[role="button"]')];
    const t=els.find(e=>/^confirm$/i.test((e.textContent||'').replace(/\s+/g,' ').trim()) && e.getBoundingClientRect().width>0);
    if(t){['mousedown','mouseup','click'].forEach(ev=>t.dispatchEvent(new MouseEvent(ev,{bubbles:true})));return true;}
    return false;
  });

  // --reset: delete the existing (junk/incomplete) FY first so the start date becomes editable
  if(RESET){
    const before=await frame.evaluate(()=>{const e=document.getElementById('edFiscalYearSetup-FirstFinYear');return e?e.value:'';});
    console.log('reset: existing FirstFinYear =', JSON.stringify(before));
    console.log('reset: Delete cmd:', await cmd(frame,'Delete')); await sleep(pg,2500);
    console.log('reset: Confirm clicked:', await clickConfirm(frame)); await sleep(pg,3000);
    // Delete only marks the row; Save commits the deletion
    console.log('reset: Save (commit delete):', await cmd(frame,'Save')); await sleep(pg,6000);
    // reload the screen to land on a clean, editable new-FY form
    await pg.goto(`${BASE}Main?ScreenId=${SCREEN}`,{waitUntil:'domcontentloaded',timeout:60000});
    await sleep(pg,10000); frame=findFrame(); if(!frame) throw new Error('frame after reset');
    const after=await frame.evaluate(()=>{const e=document.getElementById('edFiscalYearSetup-FirstFinYear');return e?{val:e.value,readonly:e.hasAttribute('readonly'),enabled:e.getAttribute('enabled')}:null;});
    console.log('reset: after delete+reload FirstFinYear =', JSON.stringify(after));
  }

  // GL101000 is a singleton setup screen (no Insert). FirstFinYear is read-only once
  // the year header exists; the editable inputs are Start Date, Period Type, #Periods.
  console.log('set FirstFinYear  ->', await setText(pg,frame,'FirstFinYear',YEAR));
  await setCombo(pg,frame,'PeriodType',PTYPE);
  console.log('set FinPeriods    ->', await setText(pg,frame,'FinPeriods',PERIODS));
  console.log('set StartDate     ->', await setText(pg,frame,'PeriodsStartDate',START));
  if(ADJ){ await frame.evaluate(id=>{const c=document.querySelector(`#ed${id} input.qp-checkbox__input`)||document.querySelector(`#ed${id}`); if(c)['mousedown','mouseup','click'].forEach(e=>c.dispatchEvent(new MouseEvent(e,{bubbles:true})));}, `${VIEW}-HasAdjustmentPeriod`); }
  await sleep(pg,1500);

  // THE key step: "Create Periods" (data-cmd=autoFill) generates the period grid.
  // This is exactly what the contract REST API cannot trigger.
  console.log('Create Periods (autoFill):', await cmd(frame,'autoFill'));
  await sleep(pg,4000);
  console.log('period grid after Create Periods:', JSON.stringify(await gridRows(frame)));

  if(DRY){ console.log('DRY run - periods generated in-page but NOT saved.'); await b.close(); return; }
  console.log('Save:', await cmd(frame,'Save'));
  await sleep(pg,9000);
  // surface any error banner
  const err=await frame.evaluate(()=>{const e=[...document.querySelectorAll('.message-text,.error,.au-error,[class*="error"]')].map(x=>(x.textContent||'').trim()).filter(Boolean);return e.slice(0,5);});
  console.log('messages:', JSON.stringify(err));
  console.log('DONE. Verify: GET FinancialYear via grp-mcp, then Generate calendar on GL201000.');
  await b.close();
})().catch(e=>{ console.error('ERR:',e.message); process.exit(1); });
